function H_k_sym = H_k_func(in1)
%H_k_func
%    H_k_sym = H_k_func(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Sep-2025 17:25:44

H_k_sym = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0],[2,4]);
end
