function Sindy_ODEs = Sindy_ODE_RHS(t,in2,in3)
%Sindy_ODE_RHS
%    Sindy_ODEs = Sindy_ODE_RHS(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    23-Jun-2025 06:45:57

z3 = in2(3,:);
z4 = in2(4,:);
Sindy_ODEs = [z3;z4;0.0;0.0];
end
