function Sindy_ODEs = Sindy_ODE_RHS(t,in2,in3)
%Sindy_ODE_RHS
%    Sindy_ODEs = Sindy_ODE_RHS(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    05-Jun-2025 08:52:50

u1 = in3(1,:);
u2 = in3(2,:);
z1 = in2(1,:);
z2 = in2(2,:);
z3 = in2(3,:);
z4 = in2(4,:);
t2 = z1.*2.0;
t3 = z2.*-1.0;
t5 = z2.*-2.0;
t7 = z3.^2;
t8 = z4.^2;
t9 = t3+z1;
t12 = t2+t5;
t10 = cos(t9);
t11 = sin(t9);
t13 = sin(t12);
t14 = t10.^2;
Sindy_ODEs = [z3;z4;(u1.*5.554233e+10+z3.*7.269208e+8-z4.*3.634604e+8+t8.*t11.*3.229288e+6+t7.*t13.*2.192267e+6+t10.*z3.*4.934848e+8-t10.*z4.*4.934848e+8)./(t14.*4.384534e+6-1.0e+7);((u2.*1.266778263209574e+4+z3.*3.485326689338035e+2-z4.*2.719169664327055e+2+t7.*t11.*3.096657620892813+t8.*t13.*5.0e-1+t10.*z3.*2.251024889431101e+2-t10.*z4.*1.12551244471455e+2).*-1.0)./(t14-2.280743864077749)];
end
