function Sindy_ODEs = Sindy_ODE_RHS(t,in2,in3)
%Sindy_ODE_RHS
%    Sindy_ODEs = Sindy_ODE_RHS(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Sep-2025 20:51:12

u1 = in3(1,:);
u2 = in3(2,:);
z2 = in2(2,:);
z3 = in2(3,:);
z4 = in2(4,:);
t2 = cos(z2);
t3 = sin(z2);
t4 = z4.*1.0e+3;
t5 = tanh(t4);
Sindy_ODEs = [z3;z4;t5.*2.026959862663825e+2+u1.*8.342920117469657e+1-u2.*2.951128752700984e+3-t2.*t5.*1.960525066903792e+2+t2.*u2.*2.94048082091345e+3-t3.*z3.*z4.*4.658465069823433e+1+t2.*t3.*z3.*z4.*5.006045255109348e+1;1.0./t2.^2.*(u1.*1.472205e+7+u2.*2.669232e+6-t2.*u1.*1.453748e+7-t2.*u2.*2.709417e+6).*-1.000000000000001e-3];
end
